<a href="https://colab.research.google.com/github/ZHAOTransparentAI/Pytorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS MATH OPERATION

*   Add, Substract, Multiply, Divdie, Remainders, Exponents
*   Shorthand and Longhand

In [31]:
import torch
import numpy as np

In [32]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([1,2,3,4])

In [38]:
# Addition
tensor_a + tensor_b

# Multiplication
tensor_a * tensor_b

# Division
tensor_a / tensor_b

tensor([1., 1., 1., 1.])

In [39]:
# Addition Longhand
torch.add(tensor_a, tensor_b)
# Substraction
torch.sub(tensor_b, tensor_a)
# Multiplication
torch.mul(tensor_a, tensor_b)
# Division
torch.div(tensor_b, tensor_a)

tensor([1., 1., 1., 1.])

In [40]:
# Reminder Modulus
tensor_b % tensor_a

tensor([0, 0, 0, 0])

In [41]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 0, 0])

In [42]:
# Exponents
torch.pow(tensor_b, tensor_a)

tensor([  1,   4,  27, 256])