<a href="https://colab.research.google.com/github/ZHAOTransparentAI/Pytorch-Tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS
Tensor is a multi-dimensional matrix containing elements of a single data type.

In [1]:
import torch
import numpy as np

In [24]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Reshape and View
my_torch = my_torch.reshape(5,-1)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
my_torch[:,1]

tensor([1, 3, 5, 7, 9])

In [29]:
# Return column
my_torch[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])