<a href="https://colab.research.google.com/github/ZHAOTransparentAI/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS
Tensor is a multi-dimensional matrix containing elements of a single data type.

In [1]:
import torch
import numpy as np

## LIST

In [2]:
my_list = [[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

## NUMPY ARRAYS

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.40524239, 0.84943935, 0.62806697, 0.30865404],
       [0.37954923, 0.27138767, 0.35194364, 0.77003878],
       [0.06247251, 0.35723249, 0.58074442, 0.54079336]])

In [8]:
np1.dtype

dtype('float64')

## TENSORS

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.6174, -0.9468, -1.2751,  1.0226],
        [-2.7983,  2.0691,  0.9115, -0.2735],
        [-0.6866,  0.6015,  0.3052, -0.0790]])

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4052, 0.8494, 0.6281, 0.3087],
        [0.3795, 0.2714, 0.3519, 0.7700],
        [0.0625, 0.3572, 0.5807, 0.5408]], dtype=torch.float64)

In [14]:
my_tensor.dtype

torch.float64